const articels = [
        {
                slug: "xuat-ban",
                article: [
                        {
                                title: "Sự nhớp nhúa của một xã hội vô cảm",
                                sapo: 'Một sự nhớp nhúa trong "Xuyên thấu" nằm ở sự vô cảm, thờ ơ, dửng dưng của xã hội.',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_20/IMG_2922.JPG",
                                slug: "su-nhop-nhua-cua-mot-xa-hoi-vo-cam",
                        },
                        {
                                title: "Khi thiên tai không còn là tự nhiên",
                                sapo: "Với tác động của con người, thiên tai đang diễn ra thường xuyên hơn và không còn là hiện tượng thuần túy xuất phát thuần túy từ thiên nhiên.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/bpivpbbx/2023_05_31/zing.png",
                                slug: "khi-thien-tai-khong-con-la-tu-nhien",
                        },
                        {
                                title: "Hai bộ sách về 'sói Wolfoo' giúp trẻ rèn luyện EQ, IQ",
                                sapo: "Nếu 'Wolfoo Ehon' tập trung phát triển trí thông minh cảm xúc (EQ) thì 'Wolfoo Khám phá' lại mang đến bài học giúp nâng cao năng lực trí tuệ (IQ).",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_30/img_1742_1_3452.jpg",
                                slug: "hai-bo-sach-ve-soi-wolfoo-giup-tre-ren-luyen-eq-iq",
                        },
                        {
                                title: "Bầu trời trong quả trứng",
                                sapo: '"Bầu trời trong quả trứng" trích từ tập thơ cùng tên của nữ sĩ Xuân Quỳnh, do Nhà xuất bản Kim Đồng ấn hành (bản in năm 2023, tái bản lần thứ bảy).',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_30/qua_trung.jpg",
                                slug: "bau-troi-trong-qua-trung",
                        },
                        {
                                title: "'Thư viện trên đá' - mang văn hóa đọc tới trẻ em vùng cao",
                                sapo: "Chương trình thiện nguyện “Cùng mang sách về miền núi, hải đảo” mùa đầu tiên với chủ đề “Thư viện trên đá”, nhằm lan tỏa giá trị của sách và văn hóa đọc.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/natmts/2023_05_30/bqd0993_1.jpg",
                                slug: "thu-vien-tren-da-mang-van-hoa-doc-toi-tre-em-vung-cao",
                        },
                        {
                                title: "Tại sao nước Biển Chết toàn muối nhưng lại có vị đắng",
                                sapo: 'Cùng là những hồ muối lớn nhưng nước tại hồ Salt Lake (Utah, Mỹ) có vị mặn dễ chịu, nước Biển Chết (Biên giới Israel và Jordan) lại có vị "đắng đến buồn nôn".',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/mzdgi/2023_05_31/bien_chet_toa_do_du_lich_doc_dao_kho_bo_qua_ivivu_5.png",
                                slug: "tai-sao-nuoc-bien-chet-toan-muoi-nhung-lai-co-vi-dang",
                        },
                        {
                                title: "Lắng nghe lời thì thầm với dòng sông",
                                sapo: 'Giống cuộc tổng kết về một đời thơ, tuyển tập "Thì thầm với dòng sông" (Mibooks và NXB Hội Nhà văn) mang đến cho bạn đọc những bài thơ tiêu biểu và đặc sắc của nhà thơ Hoài Vũ.',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_30/cn3_xnd_1025.jpg",
                                slug: "lang-nghe-loi-thi-tham-voi-dong-song",
                        },
                        {
                                title: "Đường về nhà của những người lính trong ‘Chúng tôi thời hậu chiến’",
                                sapo: "Qua dòng hồi ức của Vũ Công Chiến, cuộc sống thời hậu chiến của tác giả và đồng đội được vẽ ra bằng đủ gam màu rực rỡ, trầm buồn, nét đậm cá tính, nét thanh bay bổng…",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_30/bia_sach_chung_toi_thoi_hau_chien_1069.jpg",
                                slug: "duong-ve-nha-cua-nhung-nguoi-linh-trong-chung-toi-thoi-hau-chien",
                        },
                        {
                                title: "Annie Ernaux: 'Giải Nobel rơi vào đời tôi như một quả bom'",
                                sapo: "Trong cuộc trò chuyện với Sally Rooney, nhà văn chia sẻ giải thưởng đã cản trở khả năng tập trung sáng tác; tuy vậy bà xúc động khi thấy nhiều người đồng cảm với tác phẩm của mình.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_30/annie.jpg",
                                slug: "annie-ernaux-giai-nobel-roi-vao-doi-toi-nhu-mot-qua-bom",
                        },
                        {
                                title: "Điều bình thường không phải bậc cha mẹ nào đều nghe thấy",
                                sapo: "Anthony Guerriero từng phát triển bình thường như bao trẻ khác cho đến khi được 18 tháng.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/dqmblcvo/2023_05_28/boy_looking_through_window_treatment_for_autism_dp_FEATURE_.jpg",
                                slug: "https: //zingnews.vn/dieu-binh-thuong-khong-phai-bac-cha-me-nao-deu-nghe-thay",
                        },
                        {
                                title: "Bồi hồi khi xem tư liệu về ngày Bồ tát Thích Quảng Đức tự thiêu",
                                sapo: 'Triển lãm "Kết nên một đài sen" với hơn 100 hiện vật ấn phẩm báo chí, tư liệu tưởng niệm 60 năm Bồ tát Thích Quảng Đức vị pháp thiêu thân (1963-2023).',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/bpivpbbx/2023_05_31/monk2.jpg",
                                slug: "trien-lam-tu-lieu-ve-ngay-bo-tat-thich-quang-duc-tu-thieu",
                        },
                        {
                                title: "Cách làm sạch nguyên liệu ép, bảo quản nước ép",
                                sapo: "Chất lượng nước ép phụ thuộc nhiều vào chất lượng nguyên liệu. Trái cây và rau củ hữu cơ hoặc được trồng theo phương pháp sinh học là những lựa chọn tốt nhất.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/caxwpqdwp/2023_05_27/l_intro_1627652960.jpg",
                                slug: "cach-lam-sach-nguyen-lieu-ep-bao-quan-nuoc-ep",
                        },
                        {
                                title: "Truyện ngắn Haruki Murakami: Trên gối đá (kỳ 1)",
                                sapo: 'Truyện ngắn "Trên gối đá" do Trương Thùy Linh dịch được in trong cuốn "Ngôi thứ nhất số ít", mới xuất bản tại Việt Nam.',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_30/in_your_lap_sangeetha_bansal.jpg",
                                slug: "truyen-ngan-haruki-murakami-tren-goi-da-ky-1",
                        },
                        {
                                title: "Truyện tranh Việt dành cho tuổi trưởng thành",
                                sapo: '"Gửi em" có niềm vui của những ngày thanh xuân gian khó, nhiều vất vả bộn bề nhưng được sống trọn với đam mê.',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_28/Gui_em.jpg",
                                slug: "truyen-tranh-viet-danh-cho-tuoi-truong-thanh",
                        },
                        {
                                title: "Mệt mỏi với số hóa, độc giả quay lại với bản in",
                                sapo: "Sự lớn mạnh của những “ông lớn” công nghệ đã làm sụt giảm doanh thu của các ấn bản in. Nhưng khi độc giả mệt mỏi với xu hướng số hóa, các ấn bản in có làn sóng hồi sinh mới.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/qoswae/2023_05_30/kids_school_teen_reading_feature.jpg",
                                slug: "met-moi-voi-so-hoa-doc-gia-quay-lai-voi-ban-in",
                        },
                        {
                                title: "Đưa văn học nhà trường lên sân khấu: Sức sống mới cho nghệ thuật",
                                sapo: "Các đơn vị nghệ thuật sẽ phục dựng và dàn dựng 51 vở diễn trong 70 tác phẩm văn học đặc sắc thuộc chương trình giáo dục phổ thông, tổ chức 1.800 đến 2.000 buổi diễn cho các trường.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_20/Vo_dien_Canh_dieu_lang_Vu.jpg",
                                slug: "dua-van-hoc-nha-truong-len-san-khau-suc-song-moi-cho-nghe-thuat",
                        },
                        {
                                title: "Phát động cuộc thi sáng tác Văn chương phương Nam",
                                sapo: "Hội Nhà văn TP.HCM, tạp chí Văn nghệ TP.HCM và Đại học Cửu Long phối hợp tổ chức cuộc thi sáng tác Văn chương phương Nam dành cho học sinh, sinh viên.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_28/tet_mien_tay.jpg",
                                slug: "phat-dong-cuoc-thi-sang-tac-van-chuong-phuong-nam",
                        },
                        {
                                title: "Góc đọc sách hè dành cho bé 3-11 tuổi",
                                sapo: "Các bạn nhỏ sẽ được trải nghiệm đọc những cuốn sách thuộc nhiều thể loại: thơ, truyện, sách khoa học, kiến thức, kỹ năng…",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/natmts/2023_05_28/thumb_doc_sach.jpg",
                                slug: "goc-doc-sach-he-danh-cho-be-3-11-tuoi",
                        },
                        {
                                title: "'Muội tro' - những nốt nhạc ngân vang công lý",
                                sapo: "Tò mò và bất ngờ, đó là cảm nhận đầu tiên khi đọc tập truyện ngắn “Muội tro” của nhà văn Võ Chí Nhất, do NXB Tổng hợp TP Hồ Chí Minh phát hành gần đây.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_28/thuong_uy_vo_chi_nhat_ke_451680.jpg",
                                slug: "muoi-tro-nhung-not-nhac-ngan-vang-cong-ly",
                        },
                        {
                                title: "'Nhật ký của Anne Frank' - cuốn sách tôi không mong kết thúc",
                                sapo: "Khi quyển sách không còn được viết nữa cũng là lúc cả cô bé Anne Frank và những người còn lại cận kề cái chết. Do vậy, tôi không mong chờ cái kết.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_28/Anne_Frank_2.jpg",
                                slug: "nhat-ky-cua-anne-frank-cuon-sach-toi-khong-mong-ket-thuc",
                        },
                        {
                                title: "Mỗi mùa hoa đỏ về, hoa như mưa rơi rơi...",
                                sapo: "Sinh thời, nhà thơ Thanh Tùng tâm sự: Hễ cứ nghe điệp khúc trong bài hát ngân vang “Mỗi mùa hoa đỏ về/ Hoa như mưa rơi rơi...” là tôi thấy mình như đang bay lên, kỷ niệm xưa ùa về.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_28/Xuan_Chinh.jpg",
                                slug: "moi-mua-hoa-do-ve-hoa-nhu-mua-roi-roi",
                        },
                        {
                                title: "Mở cửa phòng trưng bày nhận diện sách lậu - sách thật",
                                sapo: "Phòng trưng bày với chủ đề “Tuần lễ nhận diện sách giáo dục và đồ chơi an toàn cho trẻ em” sẽ mở cửa từ hôm nay đến hết ngày 4/6.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_28/z4388773862353_e3bbd505ea610f86a.jpg",
                                slug: "mo-cua-phong-trung-bay-nhan-dien-sach-lau-sach-that",
                        },
                        {
                                title: "Những rung chấn đầu tiên của cuộc khủng hoảng tài chính năm 2008",
                                sapo: "Trong cuốn hồi ký, Ben S. Bernanke đã nhắc lại những rung chấn đầu tiên của của cơn bão tài chính ở nước Mỹ.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/dqmblcvo/2023_05_30/shutterstock_749993404_DMHL.jpg",
                                slug: "nhung-rung-chan-dau-tien-cua-cuoc-khung-hoang-tai-chinh-nam-2008",
                        },
                        {
                                title: "Vụ án đầu tiên của Sherlock Holmes",
                                sapo: '"Vụ án đầu tiên của Sherlock Holmes: Cuộc điều tra màu đỏ" là tác phẩm đánh dấu sự ra đời của nhân vật nổi tiếng nhất trong văn học trinh thám.',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/caxwpqdwp/2023_05_29/tai_tu_hollywood_trong_phim_sher.jpg",
                                slug: "vu-an-dau-tien-cua-sherlock-holmes",
                        },
                        {
                                title: "Goku có thực sự muốn giết thần Kai",
                                sapo: "Trong bộ “Dragon Ball Z”, Goku từng trực tiếp đe dọa thần Kai tối cao để có thể chiến đấu với Majin Vegeta. Đáng nói, vẻ mặt của Goku lúc ấy rất nghiêm túc.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/piqbzcvo/2023_05_30/Screen_Shot_2023_05_30_at_11.07.42.png",
                                slug: "goku-co-thuc-su-muon-giet-than-kai",
                        },
                        {
                                title: "Chuyện tình ‘Ở hai đầu nỗi nhớ’ của cặp trai Hà Nội, gái Sài Gòn",
                                sapo: "Ngày ấy, Chính 24 tuổi còn Mai Đào mới 20. Chàng dân Hà Nội, nàng người Sài Gòn. Tên của nàng góp cả hai loài hoa tượng trưng cho mùa xuân ở Sài Gòn và Hà Nội.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/dqmblcvo/2023_05_30/yeu_xa_16815568439961791991941.jpg",
                                slug: "chuyen-tinh-o-hai-dau-noi-nho-cua-cap-trai-ha-noi-gai-sai-gon",
                        },
                        {
                                title: "Công thức dưa muối truyền thống của người Nga",
                                sapo: "Dưa chuột muối là một trong những món ăn phổ biến tại các gia đình Nga và Ba Lan. Nhờ kỹ thuật muối, họ có thể dự trữ món ăn này trong cả mùa đông dài.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/mzdgi/2023_05_26/salted_cucumbers_one_traditional_slavic_800653_transformed.jpeg",
                                slug: "cong-thuc-dua-muoi-truyen-thong-cua-nguoi-nga",
                        },
                        {
                                title: "Hành trình chống lại khủng hoảng của người từng nắm túi tiền nước Mỹ",
                                sapo: 'Hồi ký "Dám hành động" là một cái nhìn của “người trong cuộc” về hành trình chiến đấu chống lại cuộc khủng hoảng kinh tế chỉ đứng sau Đại Khủng hoảng về quy mô.',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/dqmblcvo/2023_05_29/Ben_Bernanke_2.jpg",
                                slug: "hanh-trinh-chong-lai-khung-hoang-cua-nguoi-tung-nam-tui-tien-nuoc-my",
                        },
                        {
                                title: "Người Malaysia kéo vali đi mua sách",
                                sapo: "Hội sách Quốc tế Kuala Lumpur có hơn 200 đơn vị xuất bản, thu hút đông đảo bạn đọc Malaysia tham dự. Ngày cuối tuần, hơn 170.000 người đã đến hội sách.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/natmts/2023_05_28/malaysia.jpg",
                                slug: "nguoi-malaysia-keo-vali-di-mua-sach",
                        },
                        {
                                title: "Chọn máy ép trái cây đúng",
                                sapo: "Nếu đây là lần đầu bạn làm nước ép, bạn có rất nhiều câu hỏi nên mua loại máy ép nào, cách chuẩn bị trái cây cùng rau củ làm nguyên liệu ra sao.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/qoswae/2023_05_29/thumb_nuoc_ep.jpg",
                                slug: "chon-may-ep-trai-cay-dung",
                        },
                        {
                                title: "Đóng băng sách cổ ở -25 độ C để khôi phục sau lũ lụt",
                                sapo: "Các bản thảo quý giá được đặt trong tủ đông công nghiệp ở -25 độ C để tìm cách loại bỏ nước bị ngấm vào.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/qoswae/2023_05_29/5000_3_.jpg",
                                slug: "dong-bang-sach-co-o-25-do-c-de-khoi-phuc-sau-lu-lut",
                        },
                        {
                                title: "Sức hấp dẫn nguy hiểm trong tính nam",
                                sapo: 'Trong tập tiểu luận "The male gazed", Manuel Betancourt bóc tách cách xã hội dựng nên khái niệm "tính nam".',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_29/SCHOOL_TIES_26.jpg",
                                slug: "suc-hap-dan-nguy-hiem-trong-tinh-nam",
                        },
                        {
                                title: "Văn học trẻ trước bầu trời rộng mở",
                                sapo: "Văn học trẻ đang vận động ra sao? Nên có cái nhìn thế nào để khách quan hơn với những người viết trẻ?",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/natmts/2023_05_28/2021_05_03_16_34_45_091.jpg",
                                slug: "van-hoc-tre-truoc-bau-troi-rong-mo",
                        },
                        {
                                title: "Sôi nổi các hội sách dành cho thiếu nhi",
                                sapo: "Nhân Ngày Quốc tế thiếu nhi (1/6) và chào đón mùa hè 2023, nhiều hội sách dành cho thiếu nhi được tổ chức tại Hà Nội.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/natmts/2023_05_28/Thumbnails28342023073454Thumbnai.jpg",
                                slug: "soi-noi-cac-hoi-sach-danh-cho-thieu-nhi",
                        },
                        {
                                title: "Chiêu 'cuỗm' sách cổ quý hiếm của tiến sĩ thần học",
                                sapo: "Tính trung bình mỗi ngày trong số 450 ngày làm việc cho Thư viện công cộng Hoàng gia Nga, Tiến sĩ Thần học Elois Pichler đã trộm 10 cuốn sách cổ quý nhất.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/natmts/2023_05_28/15c_5173_2_499_299_291.jpg",
                                slug: "chieu-cuom-sach-co-quy-hiem-cua-tien-si-than-hoc",
                        },
                        {
                                title: "    Xuất bản sách của Tổng bí thư bằng 7 ngoại ngữ",
                                sapo: "Sách “Một số vấn đề lý luận và thực tiễn về chủ nghĩa xã hội và con đường đi lên chủ nghĩa xã hội ở Việt Nam” được xuất bản bằng 7 ngoại ngữ.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_17/Ra_mat_sach_Tong_bi_thu.jpg",
                                slug: "xuat-ban-sach-cua-tong-bi-thu-bang-7-ngoai-ngu",
                        },
                        {
                                title: "    Sách của Tổng bí thư trở thành tài liệu giảng dạy trong trường đại học",
                                sapo: "Sách của Tổng bí thư Nguyễn Phú Trọng là một trong các tài liệu được liệt kê trong công văn chỉ đạo về việc đưa nội dung phòng, chống tham nhũng giảng dạy tại các trường đại học.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_05_10/MG_1104_2_.JPG",
                                slug: "sach-cua-tong-bi-thu-tro-thanh-tai-lieu-giang-day-trong-truong-dai-hoc",
                        },
                        {
                                title: "Cuốn sách của Tổng bí thư thu hút độc giả cố đô Huế",
                                sapo: "Bất chấp nắng nóng, hàng nghìn lượt người dân, du khách đã đến tham quan các gian trưng bày tại Ngày Sách và Văn hóa đọc lần thứ hai diễn ra tại TP Huế.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/jugtzb/2023_04_21/3_zing_1.jpg",
                                slug: "cuon-sach-cua-tong-bi-thu-thu-hut-doc-gia-co-do-hue",
                        },
                        {
                                title: "Thị trường sách thiếu nhi Việt Nam - châu Á đang rộng mở",
                                sapo: "Hoạt động xuất bản sách cho thiếu nhi thời gian qua khá sôi động với những dòng sách hay, đẹp và có sức hấp dẫn với đông đảo bạn đọc nhỏ tuổi.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/natmts/2023_05_25/thumb_LH.jpg",
                                slug: "thi-truong-sach-thieu-nhi-viet-nam-chau-a-dang-rong-mo",
                        },
                        {
                                title: "Việt Nam là quốc gia tiêu điểm tại Hội sách thiếu nhi châu Á",
                                sapo: "Sáng 25/5, Hội sách thiếu nhi châu Á chính thức khai mạc tại Singapore. Năm nay, Việt Nam là quốc gia tiêu điểm, nhân kỷ niệm 50 năm quan hệ ngoại giao Việt Nam - Singapore.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/natmts/2023_05_25/Ban_quyen.jpg",
                                slug: "viet-nam-la-quoc-gia-tieu-diem-tai-hoi-sach-thieu-nhi-chau-a",
                        },
                        {
                                title: "    Các công ty sách góp phần tạo nên diện mạo ngành xuất bản Việt Nam",
                                sapo: "Trong 5 năm qua, các công ty sách liên kết đã đóng góp vào sự phát triển chung của ngành. Khi các đơn vị liên kết nhiều hơn, bức tranh xuất bản tăng cả chiều sâu lẫn bề rộng.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/mzdgi/2023_04_04/Lieu_Lam.jpg",
                                slug: "cac-cong-ty-sach-gop-phan-tao-nen-dien-mao-nganh-xuat-ban-viet-nam",
                        },
                ],
        },
        {
                slug: "kinh-doanh-tai-chinh",
                article: [
                        {
                                title: "Wake-up 247 'chơi lớn', tặng ngay 7 xe máy mỗi 24 giờ",
                                sapo: "Hè này, Wake-up 247 hứa hẹn đập tan lờ đờ uể oải với những phần quà hấp dẫn gồm 420 chiếc xe máy cùng hàng trăm nghìn thẻ điện thoại, tổng giá trị giải thưởng tới hơn 11 tỷ đồng.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/wyhktpu/2023_05_31/IMG_3596_1.jpg",
                                slug: "wake-up-247-choi-lon-tang-ngay-7-xe-may-moi-24-gio",
                        },
                        {
                                title: "HSBC: Kinh tế Việt Nam chưa thể vượt qua khó khăn",
                                sapo: "Báo cáo mới nhất của HSBC cho thấy hoạt động xuất khẩu vẫn còn chịu nhiều thách thức. Tuy nhiên, ngành dịch vụ của Việt Nam lại là một điểm sáng, đặc biệt là mảng du lịch.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/zyxx/2023_05_31/Anh_9_zi_1_.jpeg",
                                slug: "hsbc-kinh-te-viet-nam-chua-the-vuot-qua-kho-khan",
                        },
                        {
                                title: "Đại biểu băn khoăn lương công chức thấp hơn Campuchia, Thái Lan",
                                sapo: "Đại biểu Quốc hội đánh giá mức lương cán bộ, công chức ở Việt Nam là khá thấp so với các nước trong khu vực như Thái Lan, Malaysia, Campuchia.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/bfjysesfzyr/2023_05_31/310520230447_z4392704705152_abfb8b1ccfc296c7358b1870f4362a02.jpg",
                                slug: "dai-bieu-ban-khoan-luong-cong-chuc-thap-hon-campuchia-thai-lan",
                        },
                        {
                                title: "Đại biểu Quốc hội: Nhiều doanh nghiệp đã ‘chết lâm sàng’",
                                sapo: "Đại biểu Vũ Tiến Lộc (Hà Nội) cho rằng niềm tin kinh doanh đang ở mức thấp. Chính phủ không nên tăng thêm bất cứ loại thuế, phí, thủ tục nào trong thời điểm này.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/zyxx/2023_05_31/DBSCL_46_1_.jpeg",
                                slug: "dai-bieu-quoc-hoi-nhieu-doanh-nghiep-da-chet-lam-sang",
                        },
                        {
                                title: "Vì sao giá dầu giảm mạnh",
                                sapo: "Nền kinh tế lớn nhất thế giới đang trên bờ vực suy thoái, còn nền kinh tế thứ hai thế giới phục hồi với tốc độ chậm hơn dự kiến. Điều này tạo sức ép lớn lên giá dầu.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/asfzyreslz2/2023_01_12/gasoline.jpg",
                                slug: "vi-sao-gia-dau-giam-manh",
                        },
                        {
                                title: "Các ngân hàng trung ương sẽ tăng dự trữ vàng",
                                sapo: "Theo khảo sát của Hội đồng Vàng Thế giới, 24% ngân hàng trung ương hiện có kế hoạch mua thêm kim loại quý trong vòng 12 tháng tới.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/vpcvodbp/2023_05_31/FjasjptaAAEuvSL_1.jpeg",
                                slug: "cac-ngan-hang-trung-uong-se-tang-du-tru-vang",
                        },
                        {
                                title: "Ngân hàng Bản Việt đổi tên viết tắt thành BVBank",
                                sapo: "Ngân hàng TMCP Bản Việt vừa được Ngân hàng Nhà nước chấp thuận đổi tên viết tắt tiếng Anh từ Vietcapital Bank thành BVBank.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/vpcvodbp/2023_05_31/toa_nha_3_1.jpeg",
                                slug: "ngan-hang-ban-viet-doi-ten-viet-tat-thanh-bvbank",
                        },
                        {
                                title: "Nhà phân phối ủy quyền Apple bốc hơi gần một nửa lợi nhuận",
                                sapo: "Dù doanh thu lũy kế 4 tháng chỉ giảm 7,4%, tình trạng lãi vay tăng cao khiến lợi nhuận trước thuế của Petrosetco giảm tới 46,6%.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/rohuoct/2023_05_31/IMG_6116.jpg",
                                slug: "nha-phan-phoi-uy-quyen-apple-boc-hoi-gan-mot-nua-loi-nhuan",
                        },
                        {
                                title: "Vay cầm cố thông minh để tránh phát sinh nợ xấu",
                                sapo: "Đảm bảo trả nợ đúng hạn và thận trọng kiểm soát những khoản vay dưới thông tin cá nhân là cách người dân bảo vệ sức khỏe tín dụng, tránh phát sinh nợ xấu ngoài ý muốn.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/pwvovowk/2023_05_29/loan_thumb.jpg",
                                slug: "vay-cam-co-thong-minh-de-tranh-phat-sinh-no-xau",
                        },
                        {
                                title: "Đề xuất dùng 1 triệu tỷ vốn đầu tư công ở ngân hàng để hỗ trợ lao động",
                                sapo: "Đại biểu cho rằng có thể dùng 1 triệu tỷ đồng ngân sách đang gửi ngân hàng để hỗ trợ ngay cho người lao động hay xây dựng khu nhà ở cho công nhân... để kích cầu cho nền kinh tế.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/bfjysesfzyr/2023_05_31/pouyuen_z.jpeg",
                                slug: "de-xuat-dung-1-trieu-ty-von-dau-tu-cong-o-ngan-hang-de-ho-tro-lao-dong",
                        },
                        {
                                title: "ĐBQH: Cần cân nhắc các mục tiêu trong điều hành kinh tế - xã hội",
                                sapo: "Đại biểu Đặng Xuân Phương (Nghệ An) cho rằng cần cân nhắc hợp lý giữa các mục tiêu ngắn và dài hạn trong việc thực thi các chính sách kinh tế - xã hội.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/bfjysesfzyr/2023_05_31/Sieu_du_an_zing_15_chihung.jpg",
                                slug: "dbqh-can-can-nhac-cac-muc-tieu-trong-dieu-hanh-kinh-te-xa-hoi",
                        },
                        {
                                title: "Giá xăng ngày mai có thể tăng tới 800 đồng/lít",
                                sapo: "Do giá dầu thô tiếp tục tăng nên doanh nghiệp dự báo giá xăng dầu trong nước có thể quay đầu tăng khoảng 550-800 đồng/lít trong kỳ điều hành ngày mai.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/bfjysesfzyr/2023_05_31/xang_dau_van_hung.jpg",
                                slug: "gia-xang-ngay-mai-co-the-tang-toi-800-donglit",
                        },
                        {
                                title: "Nước cờ sớm của Quảng Ninh và nhà đầu tư chiến lược Sun Group",
                                sapo: "Với tầm nhìn chiến lược, Quảng Ninh đã đẩy mạnh mô hình tăng trưởng kinh tế từ “nâu” sang “xanh” với sự góp sức của những chủ đầu tư du lịch - nghỉ dưỡng hàng đầu.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/wyhktpu/2023_05_31/2_11_.jpg",
                                slug: "nuoc-co-som-cua-quang-ninh-va-nha-dau-tu-chien-luoc-sun-group",
                        },
                        {
                                title: "Đại biểu Quốc hội đề nghị thanh tra toàn diện bảo hiểm nhân thọ",
                                sapo: "Đại biểu Quốc hội cho biết sau nhiều kiện cáo, bức xúc của khách hàng vừa qua đã khiến cho dư luận không khỏi nghi ngại về việc tham gia bảo hiểm nhân thọ.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/bfjysesfzyr/2023_05_31/310520230955_z4391396429608_10100354ca428549815530df6d9f16f0.jpg",
                                slug: "dai-bieu-quoc-hoi-de-nghi-thanh-tra-toan-dien-bao-hiem-nhan-tho",
                        },
                        {
                                title: "Ưu tiên mua sắm công, đặt hàng sản xuất phát triển công nghiệp cơ khí",
                                sapo: "Theo chuyên gia, việc ưu tiên mua sắm công, đặt hàng những doanh nghiệp nội địa sẽ giúp thúc đẩy công nghiệp cơ khí, hình thành các doanh nghiệp lớn cho đất nước.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/ifsyq/2023_04_26/cong_nghiep_che_tao.jpg",
                                slug: "uu-tien-mua-sam-cong-dat-hang-san-xuat-phat-trien-cong-nghiep-co-khi",
                        },
                        {
                                title: "Cơ hội từ khủng hoảng trần nợ của Mỹ",
                                sapo: "Khủng hoảng trần nợ sẽ giáng đòn lên nền kinh tế dù Mỹ đã tránh được nguy cơ vỡ nợ. Tuy nhiên, giới quan sát cho rằng các nhà đầu tư có thể tìm ra cơ hội từ đây.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/asfzyreslz2/2023_03_18/1200x_1_1_.jpg",
                                slug: "co-hoi-tu-khung-hoang-tran-no-cua-my",
                        },
                        {
                                title: "Vũ Hán chật vật đòi nợ",
                                sapo: "Tình hình tài chính của các chính quyền tỉnh, thành phố tại Trung Quốc đã xấu đi đáng kể sau đại dịch. Riêng Vũ Hán mắc kẹt trong khoản nợ khó đòi lên tới 14 triệu USD.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/asfzyreslz2/2023_05_30/1200x_1_2_.jpg",
                                slug: "vu-han-chat-vat-doi-no",
                        },
                        {
                                title: "Microsoft thực sự muốn gì trong thương vụ 75 tỷ USD",
                                sapo: "Sở hữu lượng người chơi trung thành và đông đảo, việc có trong tay tựa game Call of Duty sẽ khiến Microsoft tiến thêm một bước trong công cuộc chiếm lĩnh thị trường game đám mây.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/zyxx/2023_05_30/im_661031.jpeg",
                                slug: "microsoft-thuc-su-muon-gi-trong-thuong-vu-75-ty-usd",
                        },
                        {
                                title: "Loạt 'đất vàng' ở Nha Trang sắp được đấu giá",
                                sapo: "Nhiều khu đất có vị trí đắc địa ở TP Nha Trang (Khánh Hòa) phù hợp quy hoạch, sắp được đưa ra đấu giá trong năm 2023-2024.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/nugzrd/2023_05_30/8_zing_1.jpg",
                                slug: "loat-dat-vang-o-nha-trang-sap-duoc-dau-gia",
                        },
                        {
                                title: "Dừng thực hiện chủ trương thành lập Đại học FLC",
                                sapo: "Đại học FLC từng được phê duyệt chủ trương thành lập vào năm 2019 với tổng vốn đầu tư gần 4.000 tỷ đồng, đến nay đã bị dừng thực hiện chủ trương thành lập.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/mrndcqjwq/2023_05_30/chinh_phu_dong_y_chu_truong_thanh_lap_truong_dh_flc.jpg",
                                slug: "dung-thuc-hien-chu-truong-thanh-lap-dai-hoc-flc",
                        },
                        {
                                title: "Chủ tịch TP.HCM: Sẽ thu hút được hàng trăm nghìn tỷ nhờ cơ chế đặc thù",
                                sapo: "Nếu làm tốt các cơ chế, chính sách đặc thù, TP.HCM sẽ huy động hàng trăm nghìn tỷ đồng trong 5 năm tới cho đầu tư phát triển và tạo bài học thành công thực tiễn pháp luật.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/spluwao/2022_09_20/batdongsan_thumb.jpg",
                                slug: "chu-tich-tphcm-se-thu-hut-duoc-hang-tram-nghin-ty-nho-co-che-dac-thu",
                        },
                        {
                                title: "Các hãng máy lạnh thu hàng chục tỷ đồng mỗi ngày",
                                sapo: 'Thị trường bước vào mùa nắng nóng là giai đoạn "vàng" hoạt động kinh doanh của các doanh nghiệp sản xuất máy lạnh. Ngay trong quý I, các hãng đã thu hàng chục tỷ đồng mỗi ngày.',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/bfjysesfzyr/2023_05_30/289953170_2834979633315466_542594855935663567_n.jpg",
                                slug: "cac-hang-may-lanh-thu-hang-chuc-ty-dong-moi-ngay",
                        },
                        {
                                title: "Lâm Đồng xem xét thu hồi 15.529 m2 đất dự án của Trung Nguyên Legend",
                                sapo: "UBND huyện Bảo Lâm đề nghị thu hồi đất dự án thưởng lãm và trưng bày cà phê của Trung Nguyên Legend đã bị chấm dứt hoạt động từ tháng 9/2022.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/bfjysesfzyr/2023_05_30/vubin_1.jpg",
                                slug: "lam-dong-xem-xet-thu-hoi-15529-m2-dat-du-an-cua-trung-nguyen-legend",
                        },
                        {
                                title: "Vinhomes vào top 10 chủ đầu tư hàng đầu Việt Nam",
                                sapo: "Công ty CP Vinhomes vừa được vinh danh top 10 chủ đầu tư hàng đầu Việt Nam tại lễ trao giải BCI Asia Awards lần thứ 18.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/wyhktpu/2023_05_30/dG.jpg",
                                slug: "vinhomes-vao-top-10-chu-dau-tu-hang-dau-viet-nam",
                        },
                        {
                                title: "Chính phủ tính đến cả phương án vay 10-20 tỷ USD để phát triển TP.HCM",
                                sapo: "Bộ trưởng Nguyễn Chí Dũng cho biết Chính phủ cũng cân nhắc, nghiên cứu và tính toán nhiều nguồn lực để phát triển TP.HCM, trong đó kể cả phương án vay vốn.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/iutmtn/2022_11_09/catlai_.jpg",
                                slug: "chinh-phu-tinh-den-ca-phuong-an-vay-10-20-ty-usd-de-phat-trien-tphcm",
                        },
                        {
                                title: "Thủ tướng giao 3 bộ gỡ khó cho karaoke",
                                sapo: "Thủ tướng vừa yêu cầu 3 bộ, ngành liên quan vào cuộc tháo gỡ khó khăn về phòng cháy chữa cháy cho các hộ kinh doanh karaoke.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/bfjysesfzyr/2023_05_30/MG_1202_z.jpeg",
                                slug: "thu-tuong-giao-3-bo-go-kho-cho-karaoke",
                        },
                        {
                                title: "Tòa nhà hơn 100 triệu USD của Bi Rain và Kim Tae Hee rao bán bất thành",
                                sapo: "Đến nay, tầng 1 và tầng 2 của tòa nhà thương mại này vẫn đang bị bỏ trống. Một số nguồn tin cho rằng cặp đôi đã quyết định dừng bán do không ai hỏi mua trong thời gian dài.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/zyxx/2023_05_30/fotojet_14_16854073412181826762512_0_0_418_669_crop_168540734529991519033.jpeg",
                                slug: "toa-nha-hon-100-trieu-usd-cua-bi-rain-va-kim-tae-hee-rao-ban-bat-thanh-post1435636",
                        },
                        {
                                title: "\nGiá vàng trong nước tăng vọt từ đáy một tháng\n        ",
                                sapo: "Mặt hàng vàng miếng, vàng nhẫn và vàng trang sức trong nước hôm nay (31/5) đều tăng vọt từ mức thấp nhất một tháng nhờ được hưởng lợi từ giá vàng thế giới.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/vpcvodbp/2023_05_31/DSC_0555_zing_1_1_1.jpeg",
                                slug: "gia-vang-trong-nuoc-tang-vot-tu-day-mot-thang-post1435865",
                        },
                        {
                                title: "\n            Giá vàng bật tăng\n        ",
                                sapo: "Thị trường kim loại quý khởi sắc sau một tuần ảm đạm. Niềm tin của người tiêu dùng vào triển vọng kinh tế và cơ hội việc làm đang suy yếu. Điều này giúp vàng hưởng lợi.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/asfzyreslz2/2023_04_19/1200x784.jpg",
                                slug: "gia-vang-bat-tang-post1435859",
                        },
                        {
                                title: "\n            USD bị bán tháo, giá vàng tăng vọt\n        ",
                                sapo: "Thỏa thuận về trần nợ công của Mỹ đang đứng trước thách thức đầu tiên tại Quốc hội. Tâm lý lo sợ khiến giá vàng tăng vọt, còn USD Index giảm mạnh.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/asfzyreslz2/2023_03_19/1x_1.jpg",
                                slug: "usd-bi-ban-thao-gia-vang-tang-vot-post1435740",
                        },
                        {
                                title: "\n            Phục hưng lễ hội sẽ là 'mỏ vàng' cho văn hóa, kinh tế\n        ",
                                sapo: "Văn hoá không chỉ là  một món ăn tinh thần thuần túy mà đang là một nguồn lực để phát triển kinh tế ngày càng mạnh mẽ, đóng góp vào sự phát triển của Hà Nội.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/natmts/2023_03_22/hoidenGiong4.jpg",
                                slug: "phuc-hung-le-hoi-se-la-mo-vang-cho-van-hoa-kinh-te-post1414178",
                        },
                        {
                                title: "\n            Thu hút đầu tư nước ngoài FDI\n        ",
                                sapo: 'Sách "FDI - Nhiệm vụ kép trong bối cảnh mới" của TS Phan Hữu Thắng đi sâu, nghiên cứu, làm rõ một trong những lĩnh vực trụ cột của nền kinh tế hiện nay.',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2023_01_15/z4041246715692_89efbeae58eedbf7e40e7a3cfdad9778.jpg",
                                slug: "video-thu-hut-dau-tu-nuoc-ngoai-fdi-post1394061",
                        },
                        {
                                title: "\n            Những cuốn sách được đón chờ trong năm 2023\n        ",
                                sapo: "Từ Paul Auster đến Margaret Atwood, nhiều tác giả nổi bật sẽ cho ra mắt tác phẩm mới trong năm nay.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/natmts/2023_01_01/Thiet_ke_chua_co_ten_4_.jpg",
                                slug: "nhung-cuon-sach-duoc-don-cho-trong-nam-2023-post1390118",
                        },
                ],
        },
        {
                slug: "cong-nghe",
                article: [
                        {
                                title: "Thông số ấn tượng của kính thực tế ảo Apple",
                                sapo: "Kính thực tế hỗn hợp (mixed-reality) của Apple sở hữu loạt thông số nổi bật so với các đối thủ như Quest 2 hay Quest Pro.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/ovhunst/2023_05_31/anh_thumb.jpg",
                                slug: "san-pham-moi-cua-apple-lo-thong-so-post1435900",
                        },
                        {
                                title: " Cách đơn giản giúp iPhone cũ chạy mượt trở lại",
                                sapo: "Có một số cách cải thiện khả năng hoạt động của iPhone trước khi bạn buộc phải chi số tiền khá lớn để mua thiết bị mới.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/pqmcbzwv/2023_05_29/intro_1685301319.jpg",
                                slug: "cach-don-gian-giup-iphone-cu-chay-muot-tro-lai-post1435378",
                        },
                        {
                                title: "Apple từng thử nghiệm AirPods màu hồng, tím",
                                sapo: "Apple tạo ra 5 phiên bản nguyên mẫu hộp sạc AirPods màu sắc khác nhau để phù hợp với iPhone 7. Tuy nhiên, cuối cùng họ chỉ bán duy nhất sản phẩm màu trắng.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/pqmcbzwv/2023_05_31/airpods_pink_prototype_2.jpg",
                                slug: "apple-tung-thu-nghiem-airpods-mau-hong-tim-post1435799",
                        },
                        {
                                title: "Giao trà sữa bằng drone ở Trung Quốc",
                                sapo: "Dịch vụ giao hàng bằng trực thăng không người lái đã trở thành sự thật với những ông trùm giao đồ ăn Trung Quốc.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/spluaaa/2023_05_30/621684504102_1.jpg",
                                slug: "trai-nghiem-3-lan-goi-do-an-bang-truc-thang-post1435628",
                        },
                        {
                                title: " Xuất hiện mô hình iPhone 15",
                                sapo: "Loạt ảnh mô hình cho thấy iPhone 15 vẫn có 4 phiên bản, nhiều thay đổi trong thiết kế so với thế hệ trước.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/yqdlcqrwq/2023_05_30/17930052023_copy.jpg",
                                slug: "xuat-hien-mo-hinh-iphone-15-post1435596",
                        },
                        {
                                title: "Nvidia chạm cột mốc nghìn tỷ USD",
                                sapo: "Giá cổ phiếu của nhà sản xuất chip tăng mạnh, trong bối cảnh hoạt động kinh doanh tốt và sự kỳ vọng ngày càng cao vào AI.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/ovhunst/2023_05_31/anh_thumb.jpeg",
                                slug: "von-hoa-nvidia-can-moc-nghin-ty-usd-post1435782",
                        },
                        {
                                title: "Những nâng cấp được chờ đợi nhất trên iOS 17",
                                sapo: "Phiên bản tiếp theo của hệ điều hành điện thoại iPhone được mong đợi sẽ xuất hiện tại WWDC 2023 với một loạt cải tiến đáng chú ý.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/ivpbciv2/2023_05_30/iOS_17_Title.jpg",
                                slug: "nhung-nang-cap-duoc-cho-doi-nhat-tren-ios-17-post1435552",
                        },
                        {
                                title: "Tựa game mới ghi tên mình vào 'ngôi đền huyền thoại'",
                                sapo: "Doanh số của The Witcher 3: Wild Hunt đến nay đạt hơn 50 triệu bản, trở thành một trong những game bán chạy nhất lịch sử.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/cplahuo/2023_05_30/withcer_3.jpg",
                                slug: "tua-game-moi-ghi-ten-minh-vao-ngoi-den-huyen-thoai-post1435651",
                        },
                        {
                                title: "Sếp NVIDIA được chào đón như siêu sao",
                                sapo: "Jensen Huang, giám đốc điều hành của NVIDIA, được báo chí và người hâm mộ chào đón như một siêu sao ca nhạc và thể thao khi tham dự Computex 2023.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/sfrsm/2023_05_30/5a3a3edc4aa6b51d008b619a.jpg",
                                slug: "sep-nvidia-duoc-chao-don-nhu-sieu-sao-post1435658",
                        },
                        {
                                title: "Hơn 40 triệu lượt xem video chỉ toàn màu đen, dài 24 giờ",
                                sapo: "Một đoạn clip chỉ có đúng một màn hình đen, không âm thanh, không hiệu ứng chạy suốt 24 giờ 1 phút 26 giây lại có hơn 40 triệu lượt xem.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/spluaaa/2023_05_29/ulk0riwgu0v51_1_1.jpg",
                                slug: "suc-hut-cua-video-toan-mau-den-dai-24-gio-tren-youtube-post1435280",
                        },
                        {
                                title: "Người đàn ông bị liệt 12 năm đi lại được nhờ AI đọc não",
                                sapo: "Thiết bị giải mã bằng AI ghép nối não bộ và tủy sống đã giúp một người đàn ông bị liệt từ 12 năm trước giờ đã có thể leo cầu thang và đi bộ mỗi lần hơn 100 m.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/ivpbciv2/2023_05_27/image_1_1.jpg",
                                slug: "nguoi-dan-ong-bi-liet-12-nam-di-lai-duoc-nho-ai-doc-nao-post1434712",
                        },
                        {
                                title: "Elon Musk đến Trung Quốc",
                                sapo: "Đây là lần đầu tiên Elon Musk trở lại Trung Quốc sau 3 năm.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/spluaaa/2023_05_30/7d4f013e7dc48579a369b8a72c435f37.jpg",
                                slug: "elon-musk-den-trung-quoc-post1435656",
                        },
                        {
                                title: "Ván cược với AI đưa Nvidia tới cột mốc 1.000 tỷ USD",
                                sapo: "Nhu cầu tăng vọt trong cơn sốt AI đối với bộ vi xử lý H100 là động lực chính đưa vốn hóa thị trường của Nvidia áp sát CLB nghìn tỷ USD.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/ivpbciv2/2023_05_29/107203248_1678120520555_A100_3.jpg",
                                slug: "van-cuoc-voi-ai-dua-nvidia-toi-cot-moc-1000-ty-usd-post1435487",
                        },
                        {
                                title: "Công nhân lắp ráp iPhone 15 được tăng lương, thưởng",
                                sapo: "Foxconn, nhà phân phối và đối tác gia công của Apple, vừa tăng lương và các gói thưởng cho công nhân mới tại nhà máy lắp ráp iPhone lớn nhất thế giới ở Trịnh Châu (Trung Quốc).",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/ohuokaa/2023_04_30/100642777_foxconn_worker_assembly_line_gettyp.jpg",
                                slug: "cong-nhan-lap-rap-iphone-15-duoc-tang-luong-thuong-post1427143",
                        },
                        {
                                title: "Khoảnh khắc iPhone xuất hiện không đến lần thứ hai",
                                sapo: "Chiếc iPhone đầu tiên tỏa sáng vì nó xuất hiện đúng thời điểm và đáp ứng được toàn bộ nhu cầu mà thế giới cần, một khoảnh khắc mà Apple khó lòng có thể tái hiện.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/ivpbciv2/2023_05_29/newspress_collage_25288920_16732.jpg",
                                slug: "khoanh-khac-iphone-xuat-hien-khong-den-lan-thu-hai-post1435259",
                        },
                        {
                                title: "CPU laptop AMD Ryzen 7045/7040 series có gì đặc biệt",
                                sapo: "Với nhiều điểm đáng chú ý, Ryzen 7045/7040 series là dòng CPU mới, mạnh mẽ và đa dạng công nghệ nhất của AMD dành cho laptop ở thời điểm này.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/wyhktpu/2023_05_30/1.png",
                                slug: "cpu-laptop-amd-ryzen-70457040-series-co-gi-dac-biet-post1435536",
                        },
                        {
                                title: "Chờ đợi gì trong sự kiện sắp tới của Apple?",
                                sapo: "Bên cạnh iOS 17 và iPadOS 17, Apple có thể ra mắt loạt thiết bị quan trọng tại hội nghị WWDC 2023 diễn ra vào đầu tháng 6.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/yqdlcqrwq/2023_05_28/16730052023.jpeg",
                                slug: "cho-doi-gi-trong-su-kien-sap-toi-cua-apple-post1435166",
                        },
                        {
                                title: "Nhận biết hàng giả bằng app điện thoại",
                                sapo: "Ứng dụng này có thể phân biệt hàng giả và hàng thật bằng ảnh chụp trên smartphone, cùng với các phân tích bằng AI.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/cplahuo/2023_05_29/Developer_says_its_app_can_spot_counterfeits_and_fakes_using_a_smartphone_camera.jpg",
                                slug: "nhan-biet-hang-gia-bang-app-dien-thoai-post1435395",
                        },
                        {
                                title: "Người dùng MacBook bị hỏng phím được Apple đền tiền",
                                sapo: "Những người dùng MacBook đã nộp đơn khiếu nại về việc phải trả tiền sửa chữa bàn phím cánh bướm sẽ sớm nhận khoản đền bù lên đến 395 USD từ Apple.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/sfrsm/2023_05_29/35cec7e4.jpg",
                                slug: "nguoi-dung-macbook-bi-hong-phim-duoc-apple-den-tien-post1435377",
                        },
                        {
                                title: "Foxconn tăng thưởng, thu hút công nhân lắp ráp iPhone 15",
                                sapo: "Công nhân mới sẽ nhận được khoản thưởng 424 USD khi làm việc tối thiểu 3 tháng tại nhà máy sản xuất iPhone của Foxconn tại thành phố Trịnh Châu.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/pqmcbzwv/2023_05_30/9b741158_536b_4fc4_a50c_1d48cb9660d0_ee30f0a2.jpeg",
                                slug: "foxconn-tang-thuong-thu-hut-cong-nhan-lap-rap-iphone-15-post1435501",
                        },
                        {
                                title: "Điểm khó hiểu trong vụ hành khách mở cửa thoát hiểm máy bay giữa trời",
                                sapo: "Một người bình thường không thể mở được cửa thoát hiểm khi máy bay trên cao do áp suất lớn từ môi trường bên ngoài. Đây là điểm khó hiểu trong vụ việc vừa xảy ra ở Hàn Quốc.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/sfrsm/2023_05_29/5cc07c4ab14bf43ad1220329.jpg",
                                slug: "diem-kho-hieu-trong-vu-hanh-khach-mo-cua-thoat-hiem-may-bay-giua-troi-post1435293",
                        },
                        {
                                title: "Sao trên trời sẽ 'biến mất' trong 20 năm nữa ở các thành phố",
                                sapo: "Việc sử dụng đèn điện công suất lớn gây ra hiện tượng ô nhiễm ánh sáng nghiêm trọng. Điều này có thể che lấp toàn bộ ngôi sao trên bầu trời đêm chỉ sau 2 thập kỷ nữa.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/ygtmvd/2023_05_29/RSXDH7MJ3VO2VGVVQ66P7MXRIE.jpg",
                                slug: "sao-tren-troi-se-bien-mat-trong-20-nam-nua-o-cac-thanh-pho-post1435263",
                        },
                        {
                                title: "Đánh mất sự nghiệp luật sư 30 năm vì tin vào ChatGPT",
                                sapo: "Có kinh nghiệm hơn 30 năm trong nghề, nhưng luật sư Steven Schwartz sắp đánh mất cả sự nghiệp chỉ vì một lần trót dại tin nhầm ChatGPT mà không kiểm chứng thông tin.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/spluaaa/2023_05_29/2023_02_20_135669_1676851070.jpg",
                                slug: "luat-su-bi-to-lam-gia-giay-to-vi-su-dung-chatgpt-post1435221",
                        },
                        {
                                title: "App trên Android sắp mượt như iOS",
                                sapo: "Độ mượt trên Android bị ảnh hưởng bởi hiệu ứng chuyển tiếp, do phải thiết kế trên nhiều dòng smartphone khác nhau. Tính năng mới sắp xuất hiện có thể khắc phục vấn đề này.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/ovhunst/2023_05_29/anh_thumb.jpg",
                                slug: "hoat-anh-tren-android-sap-muot-ma-nhu-ios-post1435292",
                        },
                        {
                                title: "Hậu quả khi 146 triệu tấn nước phun trào vì núi lửa tại Tonga",
                                sapo: "Vụ phun trào núi lửa tại Tonga diễn ra đầu năm 2022 đã gây ra hiện tượng “bong bóng plasma xích đạo”.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/djssp/2023_05_29/ispace.jpg",
                                slug: "hau-qua-khi-146-trieu-tan-nuoc-phun-trao-vi-nui-lua-tai-tonga-post1435262",
                        },
                        {
                                title: "HP Spectre x360 14 - laptop '2 trong 1', kiến tạo chuẩn riêng",
                                sapo: "HP Spectre x360 là một trong những laptop 2-in-1 sở hữu sự tinh tế trong thiết kế, mạnh mẽ trong hiệu suất, an toàn trong bảo mật, mang đến trải nghiệm đa năng, không gián đoạn.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/wyhktpu/2023_05_29/Hinh_3.jpg",
                                slug: "hp-spectre-x360-14-laptop-2-trong-1-kien-tao-chuan-rieng-post1435239",
                        },
                        {
                                title: "Chủ tịch Microsoft nêu mối nguy lớn nhất của AI",
                                sapo: "Ông khẳng định cần phải có ai đó chịu trách nhiệm cho các nội dung AI để bảo vệ con người trước những nguồn thông tin giả mạo, tránh bị lừa đảo bởi công nghệ cao.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/spluaaa/2023_05_27/00microsoft_smith_03_1_1832_jumb.jpg",
                                slug: "deepfake-la-moi-nguy-lon-nhat-cua-ai-post1434863",
                        },
                        {
                                title: "Người Mỹ đánh mất lòng tin vào Tesla",
                                sapo: "Dù sở hữu mẫu xe bán chạy nhất hành tinh trong 3 tháng đầu năm, thương hiệu Tesla vẫn bị người Mỹ đánh giá thấp.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/pqmcbzwv/2023_05_27/Tesla_rep._.jpg",
                                slug: "nguoi-my-danh-mat-long-tin-vao-tesla-post1434844",
                        },
                        {
                                title: "Chiếc máy tính mạnh nhất thế giới",
                                sapo: "Những hệ thống máy tính lượng tử với hàng trăm nghìn đến hàng triệu qubit đang được IBM, Google phát triển, dự kiến hoàn thành trong 10 năm tới.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/sfrsm/2023_05_27/800x_1.jpg",
                                slug: "chiec-may-tinh-manh-nhat-the-gioi-post1434821",
                        },
                        {
                                title: "Bí mật khiến Apple sắp phải trả giá ở nước Pháp",
                                sapo: "Các công tố viên ở Pháp đã mở một cuộc điều tra về nghi vấn Apple cố tình khuyến khích người dùng vứt bỏ iPhone thay vì tìm cách sửa chữa chúng.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/ivpbciv2/2023_05_27/France_Is_Fighting_To_Save_Your.jpg",
                                slug: "bi-mat-khien-apple-sap-phai-tra-gia-o-nuoc-phap-post1434885",
                        },
                        {
                                title: "Cửa hàng trực tuyến sẽ là bài thử với Apple",
                                sapo: "Doanh số smartphone tại Việt Nam trong quý I giảm 30%, một số hãng ghi nhận mức giảm trên 40%. Táo khuyết là thương hiệu duy nhất tăng trưởng về con số.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/ygtmvd/2022_10_24/IMGC9455_1_.jpg",
                                slug: "cua-hang-truc-tuyen-se-la-bai-thu-voi-apple-post1434937",
                        },
                        {
                                title: "Windows XP được hồi sinh mà không cần Microsoft",
                                sapo: "Thuật toán kích hoạt Windows XP đã bị bẻ khóa hoàn toàn, cho phép kích hoạt ngoại tuyến, không cần bản lậu và cũng không cần mã từ Microsoft.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/sfrsm/2023_05_28/5a3a3edc4aa6b51d008b619a_1.jpg",
                                slug: "windows-xp-duoc-hoi-sinh-ma-khong-can-microsoft-post1435048",
                        },
                        {
                                title: "Xuất hiện công cụ phá khóa iPhone từ xa tại Việt Nam",
                                sapo: "Lớp bảo mật, khóa từ xa qua tài khoản iCloud của iPhone không còn an toàn khi xuất hiện nhiều công cụ có thể vô hiệu hóa giải pháp này.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/ygtmvd/2023_05_27/CMP14.jpg",
                                slug: "xuat-hien-cong-cu-pha-khoa-iphone-tu-xa-tai-viet-nam-post1434866",
                        },
                        {
                                title: "Tin đồn gây thất vọng về iPhone 15 Pro Max",
                                sapo: "Chiếc iPhone cao cấp nhất của năm 2023 có thể dùng lại một số công nghệ từ thế hệ trước, kể cả cảm biến camera chính.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/pqmcbzwv/2023_05_28/MUSrGGHUWo7TsyTJzpdpik_970_80_1.jpg",
                                slug: "tin-don-gay-that-vong-ve-iphone-15-pro-max-post1435056",
                        },
                        {
                                title: "Nhiều bên thúc đẩy phổ cập 5G tại Việt Nam",
                                sapo: "Giải pháp kết nối 5G đang được thúc đẩy thương mại hóa bởi phía nhà mạng, công ty chip và nhiều thương hiệu di động trong nước.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/ygtmvd/2023_05_28/S21_2_of_197c7d6aa4235fc083_1__1.jpg",
                                slug: "nhieu-ben-thuc-day-pho-cap-5g-tai-viet-nam-post1435040",
                        },
                        {
                                title: "Đừng đặt camera an ninh tại những nơi này",
                                sapo: "Gắn camera an ninh tại vị trí không thuận lợi khiến chúng hoạt động kém hiệu quả, thậm chí làm giảm sự an toàn của ngôi nhà.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/yqdlcqrwq/2023_05_27/15127052023.jpg",
                                slug: "dung-dat-camera-an-ninh-tai-nhung-noi-nay-post1434789",
                        },
                        {
                                title: "Lý do tàu đổ bộ Mặt Trăng của Nhật Bản thất bại dù chỉ còn cách 5 km",
                                sapo: "Nếu sự cố không xảy ra, Hakuto-R sẽ là tàu đổ bộ đầu tiên do tư nhân sản xuất đáp xuống Mặt Trăng thành công.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/djssp/2023_05_27/0.jpg",
                                slug: "ly-do-tau-do-bo-mat-trang-cua-nhat-ban-that-bai-du-chi-con-cach-5-km-post1434893",
                        },
                        {
                                title: "Đài quan sát phát hiện các lỗ đen 'đâm nhau'",
                                sapo: "Đài quan sát sóng hấp dẫn giao thoa kế laser (LIGO), gồm 2 máy dò khổng lồ ở Washington và Louisiana đã hoàn thành đợt nâng cấp trị giá hàng triệu USD và hoạt động trở lại.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/sfrsm/2023_05_28/5cc07c4ab14bf43ad1220329.jpg",
                                slug: "dai-quan-sat-phat-hien-cac-lo-den-dam-nhau-post1434952",
                        },
                        {
                                title: "Những lời khuyên ‘dễ ngủ’ không nên nghe theo trên Internet",
                                sapo: "Trái với suy nghĩ của nhiều người, nằm ngửa là tư thế ngủ tệ nhất. Mọi người nên ngủ sấp hoặc nghiêng sang một bên để không gặp tình trạng ngưng thở khi ngủ.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/spluaaa/2023_05_27/31Well_SleepRX_superJumbo.jpg",
                                slug: "nhung-loi-khuyen-nguoc-doi-cho-nguoi-bi-mat-ngu-post1434760",
                        },
                        {
                                title: "Điều gì xảy ra trong não của người sắp chết",
                                sapo: "Trong quá trình con người chết đi, hoạt động sinh lý thần kinh trong bộ não gia tăng, ở cả những vùng liên quan đến quá trình xử lý có ý thức.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/sfrsm/2023_05_27/2023_04_11T004138Z_458854587_RC2.jpg",
                                slug: "dieu-gi-xay-ra-trong-nao-cua-nguoi-sap-chet-post1434792",
                        },
                        {
                                title: "Sự thật về sản phẩm 'vợ robot' của Elon Musk",
                                sapo: 'Các bài đăng trên mạng xã hội cho rằng một trong những công ty của Elon Musk sẽ cho ra mắt sản phẩm "vợ robot" vào tháng 9 tới. Tuy nhiên, đây là tin giả.',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/cplahuo/2023_05_27/elon_w_h.jpeg",
                                slug: "thuc-hu-san-pham-vo-robot-cua-elon-musk-post1434853",
                        },
                        {
                                title: "4 mẫu tai nghe true wireless trong tầm giá 4 triệu đồng",
                                sapo: "Với việc ngày càng có nhiều nhà sản xuất tham gia vào thị trường tai nghe không dây (TWS), người dùng Việt đang có thêm nhiều lựa chọn hấp dẫn ở phân khúc 3-4 triệu đồng.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/ohuokaa/2023_05_26/tai_nghe_1_1.jpg",
                                slug: "4-mau-tai-nghe-true-wireless-trong-tam-gia-4-trieu-dong-post1434563",
                        },
                        {
                                title: "Văn hóa sáng tạo của Apple\n        ",
                                sapo: 'Cuốn sách "Đến Apple học về sáng tạo" kể lại hành trình 15 năm làm việc của kỹ sư phần mềm Ken Kocienda, thể hiện văn hóa đặc trưng của Táo khuyết dưới thời Steve Jobs.',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/yqdlcqrwq/2022_10_31/00101112022.jpg",
                                slug: "sach-den-apple-hoc-ve-sang-tao-post1370451",
                        },
                        {
                                title: "\n            AI có đang cướp mất công việc của chúng ta\n        ",
                                sapo: "Giáo sư Fujimoto cho rằng con người không những không bị AI thay thế mà còn có thể tận dụng AI như một công cụ hữu ích và sinh ra lợi nhuận.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmts/2022_11_06/What_Is_The_Importance_Of_Artifi.jpg",
                                slug: "ai-co-dang-cuop-mat-cong-viec-cua-chung-ta-post1372396",
                        },
                        {
                                title: "\n            Quy định sử dụng điện thoại ở tuyển Việt Nam của HLV Park Hang-seo\n        ",
                                sapo: "Trong quá trình huấn luyện, ông Park Hang-seo yêu cầu các cầu thủ không sử dụng điện thoại trong bữa ăn, tăng giao lưu, trò chuyện để thân thiết  với nhau hơn.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/dqmblcvo/2022_11_03/dien_thoai_u22_viet_nam_10.jpg",
                                slug: "quy-dinh-su-dung-dien-thoai-o-tuyen-viet-nam-cua-hlv-park-hang-seo-post1371780",
                        },
                        {
                                title: "\n            Có nên mua máy rửa chén?\n        ",
                                sapo: "Dù mang lại nhiều công năng, tính hiệu quả, tiết kiệm thời gian…nhiều người vẫn chưa sẵn sàng sử dụng máy rửa chén do chi phí cao.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/xtsma/2022_11_30/Thumb_audio.jpg",
                                slug: "co-nen-mua-may-rua-chen-du-chi-phi-cao-post1380319",
                        },
                        {
                                title: "\n            Mua sách hay chọn máy đọc sách\n        ",
                                sapo: "Máy đọc sách là công cụ hỗ trợ tốt cho việc đọc, nhờ những lợi thế màn hình e-ink, khả năng ghi chú, nhưng nhiều người đọc sách lâu năm vẫn chưa quen sử dụng thêm thiết bị.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/xtsma/2022_11_07/Thumb_audio.jpg",
                                slug: "may-doc-sach-la-thiet-bi-ho-tro-doc-sach-post1372660",
                        },
                        {
                                title: "\n            Trạm sạc xe điện vẫn chưa phủ rộng khắp thành phố\n        ",
                                sapo: "Xe điện dần trở nên phổ biến trong thời gian gần đây, tuy nhiên số lượng trạm sạc vẫn là điều khiến nhiều người lo ngại.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/xtsma/2022_10_24/Thumb_audio.jpg",
                                slug: "tram-sac-xe-dien-van-chua-phu-rong-khap-thanh-pho-post1368194",
                        },
                ],
        },
        {
                slug: "the-thao",
                article: [
                        {
                                title: " Kỷ lục của Mourinho bị Sevilla chặn đứng",
                                sapo: "Jose Mourinho có lần đầu tiên thất bại trong một trận chung kết cúp châu Âu khi AS Roma thua Sevilla vào rạng sáng 1/6 (giờ Hà Nội).",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/zatmty/2023_06_01/2023_05_31T230003Z_211595498_UP1EJ5V1RKS03_RTRMADP_3_SOCCER_EUROPA_SEV_ROM_REPORT.JPG",
                                slug: "ky-luc-cua-mourinho-bi-sevilla-chan-dung-post1436134",
                        },
                        {
                                title: "Mourinho: 'Roma chết vì trận thua oan uổng'",
                                sapo: '"Người đặc biệt" mỉa mai trọng tài và bày tỏ sự tự hào về màn thể hiện của học trò ở chung kết Europa League.',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/neg_etpyole/2023_06_01/re.JPG",
                                slug: "mourinho-roma-chet-vi-tran-thua-oan-uong-post1436112",
                        },
                        {
                                title: "HLV Sevilla nói gì sau khi đánh bại Mourinho",
                                sapo: "Ông Jose Luis Mendilibar, HLV trưởng Sevilla, vẫn không tin rằng mình đã đánh bại được AS Roma của Jose Mourinho trong trận chung kết Europa League 2022/23.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/zatmty/2023_06_01/2023_05_31T190725Z_1486841070_UP1EJ5V1H4BGA_RTRMADP_3_SOCCER_EUROPA_SEV_ROM_REPORT.JPG",
                                slug: "hlv-sevilla-noi-gi-sau-khi-danh-bai-mourinho-post1436105",
                        },
                        {
                                title: "Bàn thua ở phút 87 tiễn Anh rời U20 World Cup",
                                sapo: "Rạng sáng 1/6, U20 Anh thua Italy 1-2 ở vòng 16 đội World Cup.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/neg_etpyole/2023_06_01/fa.JPG",
                                slug: "ban-thua-o-phut-87-tien-anh-roi-u20-world-cup-post1436102",
                        },
                        {
                                title: "MU trả Weghorst, Sabitzer về lại đội chủ quản",
                                sapo: "HLV Erik ten Hag không xem Wout Weghorst và Marcel Sabitzer có trong kế hoạch của MU ở mùa giải tới.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/mfnuy/2023_05_31/s1.jpg",
                                slug: "mu-tra-weghorst-sabitzer-ve-lai-doi-chu-quan-post1436080",
                        },
                        {
                                title: " Dybala khóc nức nở sau thất bại ở chung kết Europa League",
                                sapo: "Tiền đạo người Argentina không kìm được nước mắt sau khi Roma nhận thất bại trước Sevilla ở chung kết giải đấu cúp hạng hai châu Âu rạng sáng 1/6.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/neg_etpyole/2023_06_01/ee_1.JPG",
                                slug: "dybala-khoc-nuc-no-sau-that-bai-o-chung-ket-europa-league-post1436097",
                        },
                        {
                                title: "Benzema đạt thỏa thuận sang Saudi Arabia, nhận hơn 100 triệu euro/mùa",
                                sapo: "Tiền đạo sinh năm 1987 chuẩn bị gia nhập Al Ittihad, CLB vừa đánh bại Al Nassr của Ronaldo, trong cuộc đua vô địch Saudi Pro League 2022/23.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/neg_etpyole/2023_06_01/e.JPG",
                                slug: "benzema-dat-thoa-thuan-sang-saudi-arabia-nhan-hon-100-trieu-euromua-post1436088",
                        },
                        {
                                title: "U20 Brazil thắng 4-1 dù chơi thiếu người",
                                sapo: "Rạng sáng 1/6, Brazil mất người từ cuối hiệp một nhưng vẫn hạ Tunisia ở vòng 16 đội U20 World Cup.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/neg_etpyole/2023_06_01/e_1.JPG",
                                slug: "u20-brazil-thang-4-1-du-choi-thieu-nguoi-post1436089",
                        },
                        {
                                title: "Thầy trò Mourinho gục ngã ở chung kết Europa League",
                                sapo: "Rạng sáng 1/6, Roma hòa Sevilla 1-1 trong 120 phút, sau đó thất bại 1-4 ở loạt luân lưu chung kết giải đấu cúp hạng hai châu Âu.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/neg_etpyole/2023_06_01/sdsdsd.JPG",
                                slug: "thay-tro-mourinho-guc-nga-o-chung-ket-europa-league-post1436091",
                        },
                        {
                                title: "MU giữ chân cầu thủ đầu tiên trước phiên chợ hè",
                                sapo: "Diogo Dalot trở thành viên gạch đầu tiên trong công cuộc chuẩn bị lực lượng của HLV Erik ten Hag cho mùa giải 2023/24.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/bpivpawv/2023_05_31/dalot_1_1.jpg",
                                slug: "mu-giu-chan-cau-thu-dau-tien-truoc-phien-cho-he-post1436066",
                        },
                        {
                                title: "Tottenham ra giá bán Harry Kane cho Real Madrid",
                                sapo: "Truyền thông Tây Ban Nha cho biết Tottenham chỉ để Harry Kane rời đi nếu nhận được 100 triệu bảng (115 triệu euro).",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/wobjcak/2023_05_31/kanee.JPG",
                                slug: "tottenham-ra-gia-ban-harry-kane-cho-real-madrid-post1436011",
                        },
                        {
                                title: "Arsenal giúp tỷ phú Kroenke tăng 2 tỷ USD tài sản",
                                sapo: "Màn trình diễn ấn tượng của các đội thể thao do Stan Kroenke sở hữu khiến khối tài sản của vị tỷ phú này tăng lên đáng kể.",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/bpivpawv/2022_08_16/skysports_arsenal_josh_kroenke_4720040.jpg",
                                slug: "arsenal-giup-ty-phu-kroenke-tang-2-ty-usd-tai-san-post1436040",
                        },
                        {
                                title: "Giải mã MU",
                                sapo: "HLV Erik ten Hag đối mặt nhiều thử thách trong mùa đầu tiên nắm quyền, song vẫn giúp MU hạ cánh an toàn với vị trí thứ 3 ở Premier League và lọt vào 2 trận chung kết cúp quốc nội.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/mfnuy/2023_05_31/E5NH3DMY35P6ZLUY6A7YCMR7JQ.jpg",
                                slug: "giai-ma-mu-post1435945",
                        },
                        {
                                title: "CĐV Real Madrid chuẩn bị sẵn lễ tri ân Benzema",
                                sapo: "Truyền thông Tây Ban Nha cho biết người hâm mộ Real Madrid sẵn sàng cho kịch bản chia tay Karim Benzema ngay trong tuần này.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/wobjcak/2023_05_31/benz.JPG",
                                slug: "cdv-real-madrid-chuan-bi-san-le-tri-an-benzema-post1435999",
                        },
                        {
                                title: "Lý do Pep không để Cancelo đến Barca",
                                sapo: "Sự bất đồng về các điều khoản tài chính là nguyên nhân lớn nhất khiến đội chủ sân Camp Nou thất bại trong việc chiêu mộ Joao Cancelo ở phiên chợ tháng 1.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/bpivpawv/2023_02_04/cancelo_1.JPG",
                                slug: "ly-do-pep-khong-de-cancelo-den-barca-post1435996",
                        },
                        {
                                title: "Thành công của Haaland là cái tát cho Chelsea",
                                sapo: "Bất chấp việc tốn rất nhiều tiền để mua sắm tân binh, Chelsea vẫn cần xây dựng lại và những gì chờ đợi Mauricio Pochettino là mớ hỗn độn.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/wobjcak/2023_05_31/2023_05_28T153351Z_1608986900_UP1EJ5S178CL8_RTRMADP_3_SOCCER_ENGLAND_BRE_MCI_REPORT.JPG",
                                slug: "thanh-cong-cua-haaland-la-cai-tat-cho-chelsea-post1435958",
                        },
                        {
                                title: "Căn bệnh khiến Gal Gadot nghĩ mình kém cỏi",
                                sapo: 'Minh tinh "Wonder Woman" thừa nhận mỗi khi hành động, cô luôn nghi ngờ bản thân và lo lắng sẽ không ai thích việc mình làm.',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/neg_yslewlx/2022_05_09/gal_gadot_272947953_1180155549058626_8136958815715648639_n_1.jpg",
                                slug: "can-benh-khien-gal-gadot-nghi-minh-kem-coi-post1435928",
                        },
                        {
                                title: "Tiền đạo MU xăm hình Ronaldo lên chân",
                                sapo: 'Alejandro Garnacho thể hiện tình cảm với đàn anh người Bồ Đào Nha bằng hình xăm cùng dòng chữ "CR7" bên chân trái.',
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmzz/2023_05_31/a_2.JPG",
                                slug: "tien-dao-mu-xam-hinh-ronaldo-len-chan-post1435925",
                        },
                        {
                                title: "Neymar chỉ muốn tới MU?",
                                sapo: "Neymar được cho là sẽ không rời PSG để đến bất kỳ câu lạc bộ nào khác ngoài Manchester United ở kỳ chuyển nhượng mùa hè này. ",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/ihvunvj/2022_12_06/neymar_1.jpeg",
                                slug: "neymar-chi-muon-toi-mu-post1435912",
                        },
                        {
                                title: "Quyền lực tuyệt đối giúp Mourinho trở lại đỉnh cao",
                                sapo: "AS Roma cho Jose Mourinho cảm giác thân thuộc khi đội bóng của ông được tôn vinh ngay cả khi trình diễn thứ bóng đá không mấy đẹp mắt với số đông.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/bpivpawv/2023_05_31/mourinho.jpg",
                                slug: "quyen-luc-tuyet-doi-giup-mourinho-tro-lai-dinh-cao-post1435887",
                        },
                        {
                                title: "Madam Pang tranh cử chủ tịch LĐBĐ Thái Lan?",
                                sapo: "Trong tuyên bố gần đây, doanh nhân Madam Pang hé lộ ý định tranh cử chủ tịch Liên đoàn Bóng đá Thái Lan.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/mdf_zremxw/2023_05_31/03z_madam_pang_a.jpg",
                                slug: "madam-pang-tranh-cu-chu-tich-ldbd-thai-lan-post1435919",
                        },
                        {
                                title: "Iniesta đến Thai League?",
                                sapo: "Có nhiều thông tin cho rằng tiền vệ Andres Iniesta có thể chuyển tới Thái Lan thi đấu trong thời gian tới.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/aopuoax/2020_02_09/iniesta_chanathip_lsa.jpg",
                                slug: "iniesta-den-thai-league-post1435917",
                        },
                        {
                                title: "Busquets rời châu Âu sau khi chia tay Barca",
                                sapo: "Sergio Busquets tiết lộ Mỹ có thể là điểm dừng chân tiếp theo của anh sau khi chia tay sự nghiệp bóng đá đỉnh cao ở châu Âu.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/yrfjpyvslyr/2023_05_31/bus.jpeg",
                                slug: "busquets-roi-chau-au-sau-khi-chia-tay-barca-post1435882",
                        },
                        {
                                title: "Mourinho: Roma khác biệt vì không sa thải tôi trước chung kết",
                                sapo: "HLV Jose Mourinho cho rằng Sevilla được đánh giá cao hơn AS Roma trước trận chung kết Europa League rạng sáng 1/6 (giờ Hà Nội).",
                                avatar: "https: //znews-photo.zingcdn.me/Uploaded/mfnuy/2023_05_31/BSTTPPKESRO4JHMMXLDJNADF7U.jpg",
                                slug: "mourinho-roma-khac-biet-vi-khong-sa-thai-toi-truoc-chung-ket-post1435827",
                        },
                        {
                                title: "MU mở đường lui cho Greenwood",
                                sapo: "Manchester United sẽ cho phép Mason Greenwood trở lại thi đấu trong trường hợp đội nữ và các đối tác thương mại đồng ý.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/mfnuy/2022_08_06/mason_greenwood.jpg",
                                slug: "mu-mo-duong-lui-cho-greenwood-post1435815",
                        },
                        {
                                title: "Bayern tìm được người thay Oliver Kahn",
                                sapo: "Cựu Giám đốc Điều hành Karl-Heinz Rummenigge quay trở lại để lãnh đạo Bayern Munich vượt qua giai đoạn khó khăn.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/mfnuy/2023_05_31/54053166_605.jpg",
                                slug: "bayern-tim-duoc-nguoi-thay-oliver-kahn-post1435822",
                        },
                        {
                                title: "Messi sẽ nhận lương gấp ba Ronaldo nếu đến Saudi Arabia",
                                sapo: "Lời đề nghị trị giá 600 triệu euro mỗi năm cho Lionel Messi của chính phủ Saudi Arabia dường như đã khiến ông Jorge Messi hài lòng.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/bpivpawv/2023_05_28/messi.jpg",
                                slug: "messi-se-nhan-luong-gap-ba-ronaldo-neu-den-saudi-arabia-post1435783",
                        },
                        {
                                title: "Thủ môn mắc sai lầm ngớ ngẩn khiến đội nhà bị loại ở U20 World Cup",
                                sapo: "Thủ môn trẻ Kees Sims có màn trình diễn tệ hại trong trận thua 0-4 của U20 New Zealand trước Mỹ ở vòng 16 đội World Cup rạng sáng 31/5.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmzz/2023_05_31/ezgif.com_crop.gif",
                                slug: "thu-mon-mac-sai-lam-ngo-ngan-khien-doi-nha-bi-loai-o-u20-world-cup-post1435803",
                        },
                        {
                                title: "Đội hình trong mơ của Real Madrid ở mùa giải 2023/24",
                                sapo: "Trong trường hợp Benzema rời đi hè này, Real Madrid sẽ phải lấp chỗ trống bằng một trung phong đẳng cấp thế giới.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmzz/2023_05_30/01z_bellingham_kane_real_a_1.jpg",
                                slug: "doi-hinh-trong-mo-cua-real-madrid-o-mua-giai-202324-post1435778",
                        },
                        {
                                title: "Đại diện châu Á bật khóc sau bàn thua ở phút 90+7 tại U20 World Cup",
                                sapo: "Rạng sáng 31/5, U20 Uzbekistan để thua Israel 0-1 ở những phút cuối trận đấu thuộc vòng 16 đội U20 World Cup 2023.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmzz/2023_05_31/dsd.JPG",
                                slug: "dai-dien-chau-a-bat-khoc-sau-ban-thua-o-phut-90-7-tai-u20-world-cup-post1435800",
                        },
                        {
                                title: "Pep vượt thành tích của Mourinho tại Premier League",
                                sapo: "Cựu thuyền trưởng Barcelona được vinh danh là HLV hay nhất Ngoại hạng Anh mùa 2022/23.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/natmzz/2023_05_31/pep.JPG",
                                slug: "pep-vuot-thanh-tich-cua-mourinho-tai-premier-league-post1435796",
                        },
                        {
                                title: "\n            Cuộc hôn nhân kỳ lạ của cựu vô địch Grand Slam Li Na\n        ",
                                sapo: "Li Na, nhà vô địch Grand Slam đầu tiên của châu Á, là một nữ VĐV giàu cá tính. Một phần cá tính đó được chuyển vào trong cuốn tự truyện “Li Na: My Life” của chị.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/oplwkea/2023_05_29/News_big_LiNa.jpg",
                                slug: "cuoc-hon-nhan-ky-la-cua-cuu-vo-dich-grand-slam-li-na-post1435317",
                        },
                        {
                                title: "\n            Con đường của 'Quý ngài Borussia Dortmund'\n        ",
                                sapo: "Michael Zorc là một trong vài người quản lý bóng đá giỏi nhất thế giới. Nhờ tài năng của ông, Borussia Dortmund vẫn phát triển bền vững.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/oplwkea/2023_05_27/1108037_imgw968.jpg",
                                slug: "con-duong-cua-quy-ngai-borussia-dortmund-post1434869",
                        },
                        {
                                title: "\n            Michael Jordan thống trị làng bóng rổ thế nào\n        ",
                                sapo: "Có cuốn tiểu sử nào xứng đáng dài 700 trang không? Khi đọc “Michael Jordan: The Life” của tác giả Roland Lazenby, bạn sẽ khó câu trả lời nào khác ngoài việc gật đầu thừa nhận.",
                                avatar: "https://znews-photo.zingcdn.me/Uploaded/oplwkea/2023_04_27/michael_jordan_4.jpg",
                                slug: "michael-jordan-thong-tri-lang-bong-ro-the-nao-post1425995",
                        },
                ],
        },
];

const cates = [
        {
                name: "Xuất bản",
                sub: [
                        {
                                name: "Tin tức xuất bản",
                                slug: "tin-tuc-xuat-ban",
                        },
                        {
                                name: "Sách hay",
                                slug: "sach-hay",
                        },
                        {
                                name: "Nghiên cứu xuất bản",
                                slug: "nghien-cuu-xuat-ban",
                        },
                        {
                                name: "Tác giả",
                                slug: "tac-gia",
                        },
                        {
                                name: "Cuốn sách tôi đọc",
                                slug: "cuon-sach-toi-doc",
                        },
                ],
                slug: "xuat-ban",
        },
        {
                name: "Kinh doanh",
                sub: [
                        {
                                name: "Doanh nhân",
                                slug: "doanh-nhan",
                        },
                        {
                                name: "Bất động sản",
                                slug: "bat-dong-san",
                        },
                        {
                                name: "Tài chính - Chứng khoán",
                                slug: "tai-chinh",
                        },
                        {
                                name: "Thị trường",
                                slug: "kinh-doanh-thi-truong",
                        },
                        {
                                name: "Kinh tế số",
                                slug: "kinh-te-so",
                        },
                        {
                                name: "Tiền Của Tôi",
                                slug: "tien-cua-toi",
                        },
                        {
                                name: "Hàng không - Du lịch",
                                slug: "hang-khong",
                        },
                        {
                                name: "TTDN",
                                slug: "ttdn",
                        },
                        {
                                name: "Công nghiệp",
                                slug: "tieu-diem/cong-nghiep",
                        },
                ],
                slug: "kinh-doanh-tai-chinh",
        },
        {
                name: "Công nghệ",
                sub: [
                        {
                                name: "Blockchain",
                                slug: "blockchain",
                        },
                        {
                                name: "Mobile",
                                slug: "mobile",
                        },
                        {
                                name: "Gadget",
                                slug: "gadget",
                        },
                        {
                                name: "Internet",
                                slug: "internet",
                        },
                ],
                slug: "cong-nghe",
        },
        {
                name: "Thể thao",
                sub: [
                        {
                                name: "Bóng đá Việt Nam",
                                slug: "bong-da-viet-nam",
                        },
                        {
                                name: "Bóng đá Anh",
                                slug: "bong-da-anh",
                        },
                        {
                                name: "Võ thuật",
                                slug: "vo-thuat",
                        },
                        {
                                name: "eSports",
                                slug: "esports-the-thao",
                        },
                        {
                                name: "Hậu trường",
                                slug: "hau-truong-the-thao",
                        },
                        {
                                name: "Dinh dưỡng Thể thao",
                                slug: "dinh-duong-the-thao",
                        },
                ],
                slug: "the-thao",
        },
        {
                name: "Giải trí",
                sub: [
                        {
                                name: "Đời sống Sao",
                                slug: "doi-song-sao",
                        },
                        {
                                name: "Âm nhạc",
                                slug: "am-nhac",
                        },
                        {
                                name: "Phim ảnh",
                                slug: "phim-anh",
                        },
                        {
                                name: "Thời trang Sao",
                                slug: "thoi-trang",
                        },
                        {
                                name: "Hoa hậu",
                                slug: "tin-tuc-hoa-hau",
                        },
                ],
                slug: "giai-tri",
        },
        {
                name: "Đời sống",
                sub: [
                        {
                                name: "Giới trẻ",
                                slug: "gioi-tre",
                        },
                        {
                                name: "Xu hướng",
                                slug: "xu-huong",
                        },
                        {
                                name: "Sống đẹp",
                                slug: "song-dep",
                        },
                        {
                                name: "Gia đình",
                                slug: "doi-song-gia-dinh",
                        },
                        {
                                name: "Gender",
                                slug: "gender",
                        },
                        {
                                name: "Sự kiện",
                                slug: "su-kien",
                        },
                ],
                slug: "doi-song",
        },
        {
                name: "Xe",
                sub: [
                        {
                                name: "Ôtô",
                                slug: "oto",
                        },
                        {
                                name: "EV",
                                slug: "xe-dien",
                        },
                        {
                                name: "Đánh giá",
                                slug: "danh-gia",
                        },
                        {
                                name: "Xe máy",
                                slug: "xe-may",
                        },
                ],
                slug: "oto-xe-may",
        },
];
module.exports = { articels, cates };
